sudo: required
services:
  - docker
  
before_install:
  - docker build -t georgeneils/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run georgeneils/react-test npm test -- --coverage
  
after_install:
  - docker build -t georgeneils/multi-client ./client
  - docker build -t georgeneils/multi-nginx ./nginx
  - docker build -t georgeneils/multi-server ./server
  - docker build -t georgeneils/multi-worker ./worker
#Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push Images to Docker hub
  - docker push georgeneils/multi-client
  - docker push georgeneils/multi-nginx
  - docker push georgeneils/multi-server
  - docker push georgeneils/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-702216290187
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
